version: 2.1

executors:
  docker:
    docker:
      - image: cimg/rust:1.70.0
  arm:
    machine:
      image: ubuntu-2004:current 
    resource_class: arm.medium
    environment:
      INSTALL_RUSTUP: "1"

jobs:
  build_and_test:
    parameters:
      executor:
        type: executor
      version:
        type: string
      release:
        type: string
      features:
        type: string
    executor: << parameters.executor >>
    environment:
      MY_BUILD_FEATURES: << parameters.features >>
      MY_BUILD_RELEASE: << parameters.release >>
      MY_RUST_VERSION: << parameters.version >>
    steps:
      - checkout
      - run: if [ -n "$MY_RUST_VERSION" ]; then curl https://sh.rustup.rs -sSf | sh -s -- -y; fi
      - run: rustup default $MY_RUST_VERSION
      - run: cd typed_floats && cargo build --no-default-features --features "$MY_BUILD_FEATURES" $MY_BUILD_RELEASE
      - run: cd typed_floats && cargo test --no-default-features --features "$MY_BUILD_FEATURES" $MY_BUILD_RELEASE

workflows:
  build_and_test:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              executor: [docker, arm]
              version: [
                "stable",
                "1.70",
              ]
              release: [
                "",
                "--release",
              ]
              features: [
                  "",
                  "std",
                  "serde",
                  "libm",
                  "std,serde",
                  "std,libm",
                  "serde,libm",
                  "std,serde,libm",
              ]
