on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    permissions:
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo xtask pre-build
      - uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "typed_floats"
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
